# Generated by Django 3.0.3 on 2020-02-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picked_label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
