# Generated by Django 3.0.3 on 2020-04-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0003_image_picked_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
