# Generated by Django 3.0.5 on 2020-04-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0005_auto_20200428_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageset',
            old_name='owner',
            new_name='user',
        ),
    ]
